Feature/range picker
k8-proxy/p-ui-wireframes pull request #68
Opened 2020-10-27 19:38 UTC by olegtaranenko

curly-wurly date range picker

2020-10-28 03:47 UTC, werzl requested changes

2020-10-28 03:47 UTC, werzl commented on proto-app/src/components/UI/Daterangepicker/Daterangepicker.jsx
> +						Today: [moment().toDate(), moment().toDate()],
The ranges here should only be 1 hour, 12 hours and 24 hours,

2020-10-28 11:50 UTC, olegtaranenko commented on proto-app/src/components/UI/Daterangepicker/Daterangepicker.jsx
> +						Today: [moment().toDate(), moment().toDate()],
fixed

2020-10-29 02:43 UTC, werzl approved these changes

2020-10-29 15:32 UTC, merged